version: '3'
services:
  app:
    build: .
    ports:
      - '8003:3000'
      - '9003:9229'
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    environment:
      HOST: 0.0.0.0
  db:
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: iLrn
    volumes:
      - ./data/postgres:/var/lib/postgresql/data